### ISSUE TITLE
Rust lock issues

### ISSUE THREAD

**Issue by nygrenh** [rage/tmc-langs-rust#95]

**Comment by jolampi** [comment]
Using 0.9.3 on Windows, moving directories fail apparently due to lock files. Target directory is empty / doesn't exist.

```
$ tmc-langs-cli-x86_64-pc-windows-msvc-0.9.3.exe settings --client-name vscode_plugin move-projects-dir "d:\\tempA"
Cannot set projects-dir to a non-empty directory.
	at TMC._checkLangsResponse (d:\work\tmc-vscode\dist\extension.js:39595:33)
	at d:\work\tmc-vscode\dist\extension.js:39437:98
	at Ok.andThen (d:\work\tmc-vscode\dist\extension.js:45341:12)
	at TMC.<anonymous> (d:\work\tmc-vscode\dist\extension.js:39437:78)
	at Generator.next (<anonymous>)
	at fulfilled (d:\work\tmc-vscode\dist\extension.js:38718:58)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
